"use client"
import { db } from '@/utils/db'
import { UserAnswer } from '@/utils/schema'
import { eq } from 'drizzle-orm'
import React, { useEffect, useState, use } from 'react'
import {
    Collapsible,
    CollapsibleContent,
    CollapsibleTrigger,
} from "@/components/ui/collapsible"
import { ChevronsUpDown, UserCheck } from 'lucide-react' // Added icon for the human coach
import { Button } from '@/components/ui/button'
import { useRouter } from 'next/navigation'

function Feedback({ params }) {
    const resolvedParams = use(params); 
    
    const [feedbackList, setFeedbackList] = useState([]);
    const [overallRating, setOverallRating] = useState(0);
    const router = useRouter();

    useEffect(() => {
        GetFeedback();
    }, []);

    const GetFeedback = async () => {
        const result = await db.select()
            .from(UserAnswer)
            .where(eq(UserAnswer.mockIdRef, resolvedParams.interviewId))
            .orderBy(UserAnswer.id);

        setFeedbackList(result);
        
        if (result.length > 0) {
            const totalRating = result.reduce((sum, item) => sum + Number(item.rating), 0);
            setOverallRating((totalRating / result.length).toFixed(1));
        }
    }

    return (
        <div className='p-10 md:px-20 lg:px-40'>
            {feedbackList?.length == 0 ?
                <div className='flex flex-col gap-3'>
                    <h2 className='font-bold text-xl text-gray-500'>No Interview Feedback Record Found</h2>
                    <Button className="w-fit" onClick={() => router.replace('/dashboard')}>Go Home</Button>
                </div>
                :
                <>
                    <h2 className='text-4xl font-black text-green-500 tracking-tighter'>Congratulation!</h2>
                    <h2 className='font-bold text-2xl mt-2 text-gray-800'>Here is your interview feedback</h2>

                    <div className='bg-white p-5 rounded-xl border-2 border-gray-100 my-8 shadow-sm'>
                        <h2 className='text-primary text-xl'>
                            Your overall interview rating: <strong className='text-3xl'>{overallRating}/10</strong>
                        </h2>
                        <p className='text-sm text-gray-500 mt-2 italic'>
                            Note: This rating is generated by AI based on your overall performance.
                        </p>
                    </div>

                    <h2 className='text-gray-500 font-medium mb-5'>
                        Find below interview questions with model answers, your responses, and hybrid (AI + Human) feedback.
                    </h2>
                    
                    {feedbackList && feedbackList.map((item, index) => (
                        <Collapsible key={index} className='mt-5'>
                            <CollapsibleTrigger className='p-4 bg-gray-50 hover:bg-gray-100 transition-all border rounded-xl flex justify-between my-2 text-left gap-7 w-full font-semibold text-gray-700'>
                                {item.question} <ChevronsUpDown className='h-5 w-5 text-gray-400' />
                            </CollapsibleTrigger>
                            <CollapsibleContent className='transition-all'>
                                <div className='flex flex-col gap-4 p-4 bg-white border-x border-b rounded-b-xl'>
                                    
                                    {/* Rating */}
                                    <h2 className='text-red-600 p-3 bg-red-50/50 border border-red-100 rounded-lg font-bold'>
                                        Rating: {item.rating}
                                    </h2>

                                    {/* User Answer */}
                                    <div className='p-3 border rounded-lg bg-gray-50'>
                                        <strong className='text-gray-800 block mb-1'>Your Answer:</strong>
                                        <p className='text-sm text-gray-600'>{item.userAns}</p>
                                    </div>

                                    {/* Correct Answer */}
                                    <div className='p-3 border rounded-lg bg-green-50/30'>
                                        <strong className='text-green-800 block mb-1'>Correct Answer:</strong>
                                        <p className='text-sm text-green-700'>{item.correctAns}</p>
                                    </div>

                                    {/* AI Feedback */}
                                    <div className='p-3 border rounded-lg bg-blue-50/30'>
                                        <strong className='text-blue-800 block mb-1'>AI Feedback:</strong>
                                        <p className='text-sm text-blue-700'>{item.feedback}</p>
                                    </div>

                                    {/* NEW: Human Coach Feedback Section */}
                                    {item.humanFeedback && (
                                        <div className='p-5 border-2 border-indigo-100 rounded-xl bg-indigo-50/50 mt-2 shadow-sm'>
                                            <div className='flex items-center gap-2 mb-2'>
                                                <UserCheck className='h-5 w-5 text-indigo-600' />
                                                <strong className='text-indigo-800 text-lg'>Additional Coach Notes:</strong>
                                            </div>
                                            <p className='text-indigo-900 italic font-medium leading-relaxed bg-white/50 p-3 rounded-lg border border-indigo-50'>
                                                "{item.humanFeedback}"
                                            </p>
                                        </div>
                                    )}

                                </div>
                            </CollapsibleContent>
                        </Collapsible>
                    ))}

                    <div className='flex items-center justify-center mt-12 mb-20'>
                        <Button 
                            className='px-12 py-6 text-lg font-bold rounded-full shadow-lg' 
                            onClick={() => router.replace('/dashboard')}
                        >
                            Go Back to Dashboard
                        </Button>
                    </div>
                </>
            }
        </div>
    )
}

export default Feedback